"""analysis table

Revision ID: 480531f44b24
Revises: b559270cd58c
Create Date: 2026-09-01 23:53:08.831396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = '480531f44b24'
down_revision: Union[str, None] = 'b559270cd58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('priorities', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_engagement_id'), ['engagement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_engagement_id'))

    op.drop_table('analysis')
    # ### end Alembic commands ###
