"""phase2 scan module runs

Revision ID: b559270cd58c
Revises: e04061f19242
Create Date: 2026-09-01 23:01:46.621743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = 'b559270cd58c'
down_revision: Union[str, None] = 'e04061f19242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_module_run',
    sa.Column('scan_run_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.Enum('passive', 'active', name='modulephase', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='modulerunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_module_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_module_run_scan_run_id'), ['scan_run_id'], unique=False)

    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_out_of_scope', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('active_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('current_phase', sa.Enum('passive', 'active', name='modulephase', native_enum=False, length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_column('current_phase')
        batch_op.drop_column('active_confirmed')
        batch_op.drop_column('allow_out_of_scope')

    with op.batch_alter_table('scan_module_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_module_run_scan_run_id'))

    op.drop_table('scan_module_run')
    # ### end Alembic commands ###
