"""initial schema

Revision ID: e04061f19242
Revises: 
Create Date: 2026-09-01 22:18:28.420095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = 'e04061f19242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('roe_config_yaml', sa.Text(), nullable=False),
    sa.Column('roe_config', sa.JSON(), nullable=False),
    sa.Column('roe_config_hash', sa.String(length=64), nullable=False),
    sa.Column('authorized_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'archived', name='engagementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('llm_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('domain', 'subdomain', 'ip', 'url', 'service', 'finding', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('interest_level', sa.Enum('informational', 'notable', 'high_value', name='interestlevel', native_enum=False, length=32), nullable=False),
    sa.Column('in_scope_status', sa.Enum('in_scope', 'flagged', 'excluded', name='scopestatus', native_enum=False, length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'type', 'value', name='uq_asset_identity')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index('ix_asset_engagement_type', ['engagement_id', 'type'], unique=False)

    op.create_table('scan_run',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('roe_config_snapshot', sa.JSON(), nullable=False),
    sa.Column('roe_config_hash', sa.String(length=64), nullable=False),
    sa.Column('modules_requested', sa.JSON(), nullable=False),
    sa.Column('modules_completed', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'paused', name='scanrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_run_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_engagement_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_engagement_id'], ['engagement.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('asset_relationship',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('target_asset_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.Enum('resolves_to', 'hosts', 'discovered_via', 'subdomain_of', 'serves', name='relationshiptype', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relationship_type', name='uq_relationship')
    )
    op.create_table('audit_log_entry',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('in_scope_status', sa.Enum('in_scope', 'flagged', 'excluded', name='scopestatus', native_enum=False, length=32), nullable=False),
    sa.Column('override_used', sa.Boolean(), nullable=False),
    sa.Column('roe_config_hash', sa.String(length=64), nullable=False),
    sa.Column('request_detail', sa.JSON(), nullable=False),
    sa.Column('response_meta', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_entry', schema=None) as batch_op:
        batch_op.create_index('ix_audit_engagement_ts', ['engagement_id', 'timestamp'], unique=False)

    op.create_table('evidence',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('source_module', sa.String(length=64), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_value', sa.String(length=1024), nullable=False),
    sa.Column('polarity', sa.Enum('present', 'absent', name='findingpolarity', native_enum=False, length=32), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_asset', ['asset_id'], unique=False)
        batch_op.create_index('ix_evidence_engagement_subject', ['engagement_id', 'subject_type', 'subject_value'], unique=False)

    op.create_table('session',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_token_hash'))

    op.drop_table('session')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_engagement_subject')
        batch_op.drop_index('ix_evidence_asset')

    op.drop_table('evidence')
    with op.batch_alter_table('audit_log_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_engagement_ts')

    op.drop_table('audit_log_entry')
    op.drop_table('asset_relationship')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_run_engagement_id'))

    op.drop_table('scan_run')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_engagement_type')

    op.drop_table('asset')
    op.drop_table('engagement')
    # ### end Alembic commands ###
