"""Translate the guided 'New Engagement' form into an RoE YAML document.

The form is a convenience layer only: its output goes through exactly the same
``load_roe`` validation as a hand-authored file, and the generated YAML is what
gets stored verbatim - so the operator can read it back and later edit it by
hand if they outgrow the form.
"""

from __future__ import annotations

from typing import Any

import yaml


def _lines(raw: str | None) -> list[str]:
    if not raw:
        return []
    out: list[str] = []
    for line in raw.replace(",", "\n").splitlines():
        item = line.strip()
        if item:
            out.append(item)
    return out


def _datetime_local_to_z(value: str | None) -> str | None:
    """<input type=datetime-local> yields 'YYYY-MM-DDTHH:MM' with no timezone.

    We treat the operator's input as UTC and normalise to an explicit 'Z'.
    """
    if not value:
        return None
    v = value.strip()
    if len(v) == 16:  # no seconds
        v += ":00"
    if not v.endswith(("Z", "+00:00")):
        v += "Z"
    return v


class RoEFormError(ValueError):
    pass


def form_to_roe_yaml(form: dict[str, Any]) -> str:
    def get(key: str) -> str:
        return str(form.get(key, "") or "").strip()

    name = get("name")
    client = get("client")
    if not name or not client:
        raise RoEFormError("Engagement name and client are required.")

    doc: dict[str, Any] = {
        "engagement": {"name": name, "client": client},
        "scope": {"in_scope": {}, "excluded": {}},
        "rate_limits": {},
        "evasion": {},
        "llm": {},
    }

    start = _datetime_local_to_z(get("window_start"))
    end = _datetime_local_to_z(get("window_end"))
    if bool(start) ^ bool(end):
        raise RoEFormError("Provide both a start and an end for the authorized window, or neither.")
    if start and end:
        doc["engagement"]["authorized_window"] = {"start": start, "end": end}

    domains = _lines(get("in_domains"))
    if get("include_subdomains") in ("on", "true", "1"):
        for d in list(domains):
            if not d.startswith("*.") and f"*.{d}" not in domains:
                domains.append(f"*.{d}")
    in_scope = {
        "domains": domains,
        "hosts": _lines(get("in_hosts")),
        "cidrs": _lines(get("in_cidrs")),
    }
    excluded = {
        "domains": _lines(get("ex_domains")),
        "hosts": _lines(get("ex_hosts")),
        "cidrs": _lines(get("ex_cidrs")),
    }
    doc["scope"]["in_scope"] = {k: v for k, v in in_scope.items() if v}
    doc["scope"]["excluded"] = {k: v for k, v in excluded.items() if v}
    if not doc["scope"]["in_scope"]:
        raise RoEFormError("Define at least one in-scope domain, host, or CIDR.")

    try:
        rps = float(get("max_rps") or 10)
        conc = int(get("max_conc") or 20)
    except ValueError as exc:
        raise RoEFormError(f"Rate-limit values must be numeric ({exc}).") from exc
    doc["rate_limits"] = {
        "max_requests_per_second": rps,
        "max_concurrent_connections": conc,
    }

    try:
        jit_min = int(get("jitter_min") or 100)
        jit_max = int(get("jitter_max") or 1500)
    except ValueError as exc:
        raise RoEFormError(f"Jitter values must be whole numbers of milliseconds ({exc}).") from exc
    doc["evasion"] = {
        "jitter": {
            "enabled": get("jitter_enabled") in ("on", "true", "1"),
            "min_ms": jit_min,
            "max_ms": jit_max,
        },
        "user_agents": _lines(get("user_agents")),
        "rotation_strategy": get("rotation_strategy") or "round_robin",
    }

    doc["llm"] = {"analysis_enabled": get("llm_enabled") in ("on", "true", "1")}

    header = (
        "# Generated by the guided New Engagement form.\n"
        "# This YAML is the source of truth for scope and evasion - edit it directly\n"
        "# if you need options the form does not expose.\n"
    )
    return header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
